export interface TranscriptSegment {
  id: number;
  start: number; // in seconds
  duration: number; // in seconds
  end: number; // in seconds
  timestamp: string; // formatted "MM:SS" or "HH:MM:SS"
  text: string;
}

export interface CaptionLanguage {
  code: string;
  name: string;
  isAutoGenerated?: boolean;
  isDefault?: boolean;
  vssId?: string;
}

export interface VideoMetadata {
  id: string;
  title: string;
  author: string;
  authorUrl?: string;
  lengthSeconds: number;
  durationFormatted: string;
  thumbnailUrl: string;
  views?: string;
  url: string;
}

export type TranscriptErrorCode =
  | 'INVALID_URL'
  | 'NO_CAPTIONS'
  | 'VIDEO_NOT_FOUND'
  | 'PRIVATE_VIDEO'
  | 'LIVE_STREAM'
  | 'RATE_LIMITED'
  | 'FETCH_ERROR'
  | 'NETWORK_ERROR'
  | 'UNKNOWN';

export interface ErrorScenarioDetail {
  code: TranscriptErrorCode;
  title: string;
  message: string;
  suggestions: string[];
  retryable: boolean;
}

export interface TranscriptResponse {
  success: boolean;
  video: VideoMetadata;
  segments: TranscriptSegment[];
  availableLanguages: CaptionLanguage[];
  selectedLanguage: CaptionLanguage;
  fullText: string;
  wordCount: number;
  error?: string;
  errorCode?: TranscriptErrorCode;
  errorDetails?: ErrorScenarioDetail;
  retryAfter?: number; // seconds
}

export type CopyFormat = 'text-only' | 'with-timestamps' | 'markdown' | 'bilingual';

export type ExportFormat = 'txt-timestamps' | 'txt-plain' | 'srt' | 'vtt' | 'pdf' | 'markdown';

export type TranscriptViewMode = 'original' | 'translated' | 'side-by-side';

export interface TargetTranslationLanguage {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export interface TranslatedTranscriptData {
  targetLanguage: TargetTranslationLanguage;
  segments: TranscriptSegment[];
  fullText: string;
  wordCount: number;
}

export interface TranslationResponse {
  success: boolean;
  targetLanguage?: TargetTranslationLanguage;
  segments?: TranscriptSegment[];
  fullText?: string;
  wordCount?: number;
  error?: string;
}

export interface KeyMoment {
  id: string;
  start: number;
  end: number;
  timestamp: string;
  title: string;
  summary: string;
  keywords: string[];
  startSegmentId: number;
  confidence?: 'high' | 'medium';
}

export interface HistoryItem {
  id: string;
  videoId: string;
  title: string;
  author: string;
  thumbnailUrl: string;
  durationFormatted: string;
  url: string;
  fetchedAt: number; // timestamp
  wordCount: number;
  segmentCount: number;
  language: string;
  snippet: string;
  data: TranscriptResponse;
}
